/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LevelsNode from "./Script/Project/LevelsNode"
import GameControl from "./Script/Project/GameControl"
import Balloon from "./Script/Project/Balloon"
import Balloon_Icon from "./Script/Project/Balloon_Icon"
import GameOver from "./Script/Project/GameOver"
import Ranking from "./Script/Project/Ranking"
import StartGame from "./Script/Project/StartGame"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Scenes/MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=true;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Script/Project/LevelsNode.ts",LevelsNode);
        reg("Script/Project/GameControl.ts",GameControl);
        reg("Script/Project/Balloon.ts",Balloon);
        reg("Script/Project/Balloon_Icon.ts",Balloon_Icon);
        reg("Script/Project/GameOver.ts",GameOver);
        reg("Script/Project/Ranking.ts",Ranking);
        reg("Script/Project/StartGame.ts",StartGame);
    }
}
GameConfig.init();