/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Login from "./Script/Login"
import AddLevels from "./Script/AddLevels"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="Scenes/MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Script/Login.ts",Login);
        reg("Script/AddLevels.ts",AddLevels);
    }
}
GameConfig.init();